// Firms (advisors) from a run file → idempotent SQL. The run-file format is the contract between Claude (/find-advisors)
// and any scraper Hentus builds: both write the same JSON, and this is the one importer.  See research/advisors/README.md.
export const REQUIRED_FOR_SCRAPEABLE = ['name', 'registered_name|registration_number', 'category', 'country', 'city', 'phone', 'website', 'email|contact_url', 'source_url'];

const q = (v) => (v === undefined || v === null || v === '' ? 'null' : typeof v === 'number' ? String(v) : typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => `'{${(a ?? []).map((s) => `"${String(s).replace(/(["\\])/g, '\\$1')}"`).join(',')}}'`;
const key = (a) => `${a.country}|${String(a.registered_name ?? a.name).trim().toLowerCase()}|${String(a.city ?? '').trim().toLowerCase()}`;

/**
 * @param run     the parsed run file
 * @param known   { categories: Set<string>, taxTypes: Set<string>, services: Set<string> }  codes that exist (or will, via run.categories)
 * @returns       { sql, errors, counts }
 */
export function advisorsSql(run, known) {
  const errors = [];
  const day = run.run;
  if (!day) errors.push('run date missing ("run": "yyyy-mm-dd")');
  const newCats = new Set((run.categories ?? []).map((c) => c.code));
  const cats = new Set([...known.categories, ...newCats]);
  const sources = run.sources ?? [];
  const urls = new Set(sources.map((s) => s.list_url));
  const out = [`-- GENERATED by research/apply-advisors.mjs from run ${day} — do not edit.`, 'set search_path = offshore_insights;', ''];

  for (const c of run.categories ?? []) {
    if (!c.code || !c.label) errors.push(`category needs code and label: ${JSON.stringify(c)}`);
    out.push(`insert into advisor_category (code, label, sort_order) values (${q(c.code)}, ${q(c.label)}, ${c.sort_order ?? 100}) on conflict (code) do update set label = excluded.label;`);
  }
  for (const s of sources) {
    for (const f of ['name', 'scope', 'list_url', 'collection']) if (!s[f]) errors.push(`source ${s.list_url ?? s.name ?? '?'}: ${f} missing`);
    if (s.collection && !['scrapeable', 'claude', 'manual'].includes(s.collection)) errors.push(`source ${s.list_url}: collection must be scrapeable | claude | manual`);
    if (s.collection === 'manual' && !s.instructions) errors.push(`source ${s.list_url}: a manual source needs "instructions" for Hentus`);
    if (s.collection === 'scrapeable') {
      if (!s.field_map || !s.pagination) errors.push(`source ${s.list_url}: a scrapeable source needs "field_map" and "pagination" (the scraper contract)`);
    }
    out.push(`insert into advisor_source (name, scope, country_code, list_url, kind, collection, access, fields_present, pagination, detail_pattern, field_map, instructions, notes, sampled_on, last_collected_on)`
      + ` values (${q(s.name)}, ${q(s.scope)}, ${q(s.country)}, ${q(s.list_url)}, ${q(s.kind)}, ${q(s.collection)}, ${q(s.access ?? 'open')}, ${arr(s.fields_present)}, ${q(s.pagination)}, ${q(s.detail_pattern)},`
      + ` ${s.field_map ? q(JSON.stringify(s.field_map)) + '::jsonb' : 'null'}, ${q(s.instructions)}, ${q(s.notes)}, ${q(s.sampled_on ?? day)}, ${q(s.last_collected_on ?? null)})`
      + ` on conflict (list_url) do update set name = excluded.name, scope = excluded.scope, country_code = excluded.country_code, kind = excluded.kind, collection = excluded.collection,`
      + ` access = excluded.access, fields_present = excluded.fields_present, pagination = excluded.pagination, detail_pattern = excluded.detail_pattern, field_map = excluded.field_map,`
      + ` instructions = excluded.instructions, notes = excluded.notes, sampled_on = excluded.sampled_on, last_collected_on = coalesce(excluded.last_collected_on, advisor_source.last_collected_on);`);
  }

  const seen = new Map();
  for (const a of run.advisors ?? []) {
    const id = `${a.name ?? '?'} (${a.country ?? '?'})`;
    for (const f of ['name', 'category', 'country', 'collected_by']) if (!a[f]) errors.push(`${id}: ${f} missing`);
    if (a.category && !cats.has(a.category)) errors.push(`${id}: unknown category "${a.category}" (add it under "categories" in the run)`);
    for (const c of a.categories ?? []) if (!cats.has(c)) errors.push(`${id}: unknown category "${c}"`);
    if (a.collected_by && !['scraper', 'claude', 'manual'].includes(a.collected_by)) errors.push(`${id}: collected_by must be scraper | claude | manual`);
    if (a.region && a.country && !a.region.startsWith(a.country + '-')) errors.push(`${id}: region ${a.region} is not a region of ${a.country}`);
    for (const t of a.tax_topics ?? []) if (!known.taxTypes.has(t)) errors.push(`${id}: unknown tax topic ${t}`);
    for (const t of a.services ?? []) if (!known.services.has(t)) errors.push(`${id}: unknown service ${t}`);
    if (a.source && !urls.has(a.source) && !known.sourceUrls?.has(a.source)) errors.push(`${id}: source ${a.source} is not listed under "sources"`);
    if (a.name && a.country) { const k = key(a); if (seen.has(k)) errors.push(`${id}: duplicate of "${seen.get(k)}" (same registered name and city)`); else seen.set(k, a.name); }

    out.push(`-- ${a.name} (${a.country}${a.region ? ', ' + a.region : ''}, ${a.category})`);
    out.push(`insert into advisor (name, registered_name, registration_number, legal_form, parent_group, founded_year, category_code, categories, country_code, region_code, city, address, postal_code, lat, lon, other_offices,`
      + ` phone, email, website, contact_url, linkedin_url, segment, tier, ranking_source, size_note, languages, practice_areas, tax_topics, services, mentions_hubs, notes,`
      + ` source_id, source_url, found_via, collected_by, found_on, verified_on, status) values (`
      + [q(a.name), q(a.registered_name), q(a.registration_number), q(a.legal_form), q(a.parent_group), q(a.founded_year), q(a.category), arr(a.categories), q(a.country), q(a.region), q(a.city), q(a.address), q(a.postal_code),
        q(a.lat), q(a.lon), q(a.other_offices), q(a.phone), q(a.email), q(a.website), q(a.contact_url), q(a.linkedin_url), q(a.segment), q(a.tier), q(a.ranking_source), q(a.size_note),
        arr(a.languages), arr(a.practice_areas), arr(a.tax_topics), arr(a.services), q(a.mentions_hubs), q(a.notes),
        a.source ? `(select id from advisor_source where list_url = ${q(a.source)})` : 'null', q(a.source_url), q(a.found_via), q(a.collected_by), q(a.found_on ?? day), q(a.verified_on ?? null), q(a.status ?? 'candidate')].join(', ')
      + `) on conflict (country_code, lower(coalesce(registered_name, name)), coalesce(lower(city), '')) do update set`
      + ` name = excluded.name, registration_number = coalesce(excluded.registration_number, advisor.registration_number), category_code = excluded.category_code, categories = excluded.categories,`
      + ` region_code = coalesce(excluded.region_code, advisor.region_code), address = coalesce(excluded.address, advisor.address), postal_code = coalesce(excluded.postal_code, advisor.postal_code),`
      + ` phone = coalesce(excluded.phone, advisor.phone), email = coalesce(excluded.email, advisor.email), website = coalesce(excluded.website, advisor.website),`
      + ` contact_url = coalesce(excluded.contact_url, advisor.contact_url), linkedin_url = coalesce(excluded.linkedin_url, advisor.linkedin_url), segment = coalesce(excluded.segment, advisor.segment),`
      + ` tier = coalesce(excluded.tier, advisor.tier), ranking_source = coalesce(excluded.ranking_source, advisor.ranking_source), languages = excluded.languages,`
      + ` practice_areas = excluded.practice_areas, tax_topics = excluded.tax_topics, services = excluded.services, mentions_hubs = coalesce(excluded.mentions_hubs, advisor.mentions_hubs),`
      + ` source_id = coalesce(excluded.source_id, advisor.source_id), source_url = coalesce(excluded.source_url, advisor.source_url), found_via = excluded.found_via,`
      + ` verified_on = coalesce(excluded.verified_on, advisor.verified_on);`);
  }
  out.push('', 'reset search_path;', '');
  return { sql: out.join('\n'), errors, counts: { categories: (run.categories ?? []).length, sources: sources.length, advisors: (run.advisors ?? []).length } };
}

/** How complete a source's listing is for the scraper contract: which required fields appear on every sampled entry. */
export function completeness(fieldsPresent) {
  const have = new Set(fieldsPresent);
  const missing = REQUIRED_FOR_SCRAPEABLE.filter((f) => !f.split('|').some((alt) => have.has(alt)));
  return { ok: missing.length === 0, missing };
}
