// Turn a research run (research/runs/<date>.json) into idempotent SQL:
//   node research/apply-run.mjs research/runs/2026-09-30.json   → db/research/2026-09-30.sql
//   bash db/apply.sh db/research/2026-09-30.sql
// A run file may hold, in the order they are written to the SQL:
//   jurisdictions[]  create or update a country/region (capital, tax year, regional taxes, structure ...)
//   rates[]          tax rates. mode "history" (default): a changed headline/min/max closes the current row and
//                    opens a new one; an unchanged value only refreshes verification fields.
//                    mode "correct": replaces draft rows in place (used once, for the first pass over the seed).
//                    Optional per entry: `from` (the date the value took effect; default the run date) and
//                    `to` (makes it a CLOSED back-year row [from, to), upserted by jurisdiction + type + from),
//                    `verified_on` (the date of the dated snapshot/source it was read from).
//   treaties[]       status, notes, WHT, and the dates signed_on / in_force_on
//   gates[]          blacklist / trust recognition
//   wealth[]         money figures. Either { j, year, source, <column>: n } or the report shape
//                    { source, year, column, values: { CC: n } }; ref_date = the date the figure is "as at".
//   gaps[]           research_item rows: what is missing/blocked and where to get it
// Rules (research/README.md): unknown stays unknown, every value traces to a recipe.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const file = process.argv[2];
if (!file) { console.error('usage: node research/apply-run.mjs research/runs/<date>.json'); process.exit(2); }
const run = JSON.parse(readFileSync(file, 'utf8'));
const recipes = Object.fromEntries(JSON.parse(readFileSync(join(here, 'recipes.json'), 'utf8')).recipes.map((r) => [r.id, r]));
const mode = run.mode === 'correct' ? 'correct' : 'history';
const day = run.run;

const q = (v) => (v === undefined || v === null ? 'null' : typeof v === 'number' ? String(v) : typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => q('{' + a.map((s) => String(s).replace(/[{},"\\]/g, '')).join(',') + '}');
const pick = (map, j) => map?.[j] ?? map?.[j.split('-')[0]] ?? map?.['*'];
const errors = [];
const src = (x) => {
  const r = recipes[x.recipe];
  if (!r) errors.push(`unknown recipe ${x.recipe} (${x.j ?? x.a}:${x.t ?? x.b ?? x.column ?? ''})`);
  return x.source_override ?? r?.url ?? null;
};

const out = [`-- GENERATED by research/apply-run.mjs from ${basename(file)} (mode: ${mode}) — do not edit.`,
  `-- Every value traces to a recipe in research/recipes.json.`, 'set search_path = offshore_insights;', ''];

// ── jurisdictions ────────────────────────────────────────────────────────────
// column ← run key. Only the keys present are written, so a partial entry never blanks anything.
const JCOLS = { name: 'name', parent_code: 'parent', kind: 'kind', currency: 'currency', tax_year_start: 'tax_year_start',
  next_budget_date: 'next_budget_date', is_offshore_hub: 'is_offshore_hub', notes: 'notes', lon: 'lon', lat: 'lat',
  regional_tax_types: 'regional_tax_types', capital: 'capital', capital_lon: 'capital_lon', capital_lat: 'capital_lat', iso3: 'iso3',
  sort_order: 'sort_order', estate_basis: 'estate_basis', structure_checked_on: 'structure_checked_on', structure_note: 'structure_note' };
const jval = (col, v) => (col === 'regional_tax_types' ? arr(v) : q(v));
// Countries before their regions (the parent must exist first).
const js = [...(run.jurisdictions ?? [])].sort((a, b) => (a.parent ? 1 : 0) - (b.parent ? 1 : 0));
for (const x of js) {
  const cols = Object.entries(JCOLS).filter(([, k]) => x[k] !== undefined);
  out.push(`-- jurisdiction ${x.code}${x.parent ? ' (region of ' + x.parent + ')' : ''}`);
  if (x.name && x.currency) {
    const names = ['code', ...cols.map(([c]) => c)];
    out.push(`insert into jurisdiction (${names.join(', ')}) values (${[q(x.code), ...cols.map(([c, k]) => jval(c, x[k]))].join(', ')})`
      + ` on conflict (code) do update set ${cols.map(([c]) => `${c} = excluded.${c}`).join(', ')};`);
  } else if (cols.length) {
    out.push(`update jurisdiction set ${cols.map(([c, k]) => `${c} = ${jval(c, x[k])}`).join(', ')} where code = ${q(x.code)};`);
  }
}
if (js.length) out.push('');

// ── rates ────────────────────────────────────────────────────────────────────
for (const x of run.rates ?? []) {
  const vf = pick(run.defaults?.valid_from, x.j), nc = pick(run.defaults?.next_check_on, x.j);
  const min = x.min ?? x.h, max = x.max ?? x.h;
  const verified = x.verified_on ?? day;
  const cols = { headline_rate: x.h, rate_min: min, rate_max: max, threshold_amount: x.thr, threshold_note: x.thr_note, note: x.note,
    source_url: src(x), verified_on: verified, next_check_on: x.to ? (nc ?? x.to) : nc, needs_verification: !!x.nv };
  const names = Object.keys(cols);
  const val = (k) => (k === 'needs_verification' ? String(cols[k]) : q(cols[k]));
  const key = `jurisdiction_code = ${q(x.j)} and tax_type_code = ${q(x.t)}`;
  if (x.to) {
    // A closed back-year row [from, to): upsert by jurisdiction + type + from.
    if (!x.from) { errors.push(`${x.j}:${x.t} has "to" but no "from"`); continue; }
    out.push(`-- ${x.j} ${x.t} ${x.from}..${x.to} (back-year) ← ${x.recipe}`);
    out.push(`update tax_rate set ${names.map((k) => `${k} = ${val(k)}`).join(', ')}, valid_to = ${q(x.to)} where ${key} and valid_from = ${q(x.from)};`);
    out.push(`insert into tax_rate (jurisdiction_code, tax_type_code, valid_from, valid_to, ${names.join(', ')})`
      + ` select ${q(x.j)}, ${q(x.t)}, ${q(x.from)}, ${q(x.to)}, ${names.map(val).join(', ')}`
      + ` where not exists (select 1 from tax_rate where ${key} and valid_from = ${q(x.from)});`);
    continue;
  }
  const eff = x.from ?? day;   // when the new value took effect
  out.push(`-- ${x.j} ${x.t} ← ${x.recipe}`);
  if (mode === 'history') {
    out.push(`update tax_rate set valid_to = ${q(eff)} where ${key} and valid_to is null${x.from ? ` and valid_from < ${q(x.from)}` : ''}`
      + ` and (headline_rate is distinct from ${q(x.h)} or rate_min is distinct from ${q(min)} or rate_max is distinct from ${q(max)});`);
  }
  out.push(`insert into tax_rate (jurisdiction_code, tax_type_code, valid_from, ${names.join(', ')})`
    + ` values (${q(x.j)}, ${q(x.t)}, ${q(mode === 'history' ? eff : vf)}, ${names.map(val).join(', ')})`
    + ` on conflict (jurisdiction_code, tax_type_code) where valid_to is null do update set `
    + names.map((k) => `${k} = excluded.${k}`).join(', ') + (mode === 'correct' ? ', valid_from = excluded.valid_from' : '') + ';');
}
out.push('');

// ── treaties ─────────────────────────────────────────────────────────────────
for (const t of run.treaties ?? []) {
  const set = ['status = excluded.status', 'mli_note = coalesce(excluded.mli_note, treaty.mli_note)', 'source_url = excluded.source_url',
    'verified_on = excluded.verified_on', 'next_check_on = excluded.next_check_on',
    'wht_dividend = coalesce(excluded.wht_dividend, treaty.wht_dividend)', 'wht_interest = coalesce(excluded.wht_interest, treaty.wht_interest)'];
  const dated = t.signed_on !== undefined || t.in_force_on !== undefined;
  if (dated) set.push('signed_on = coalesce(excluded.signed_on, treaty.signed_on)', 'in_force_on = coalesce(excluded.in_force_on, treaty.in_force_on)');
  out.push(`-- treaty ${t.a}-${t.b} ← ${t.recipe}`);
  out.push(`insert into treaty (country_a, country_b, status, mli_note, wht_dividend, wht_interest, source_url, verified_on, next_check_on${dated ? ', signed_on, in_force_on' : ''})`
    + ` values (${q(t.a)}, ${q(t.b)}, ${q(t.status)}, ${q(t.note)}, ${q(t.wht_dividend)}, ${q(t.wht_interest)}, ${q(src(t))}, ${q(day)}, ${q(t.next_check ?? '2027-03-31')}${dated ? `, ${q(t.signed_on)}, ${q(t.in_force_on)}` : ''})`
    + ` on conflict (country_a, country_b) do update set ${set.join(', ')};`);
}

// ── gates ────────────────────────────────────────────────────────────────────
for (const g of run.gates ?? []) {
  out.push(`-- gate ${g.j} ${g.gate}${g.hub ? ' ' + g.hub : ''} ← ${g.recipe}`);
  out.push(`insert into jurisdiction_gate (jurisdiction_code, hub, gate, status, label, note, source_url, verified_on, next_check_on, needs_verification)`
    + ` values (${q(g.j)}, ${q(g.hub)}, ${q(g.gate)}, ${q(g.status)}, ${q(g.label)}, ${q(g.note)}, ${q(src(g))}, ${q(day)}, ${q(g.next_check ?? '2027-01-15')}, ${!!g.nv})`
    + ` on conflict (jurisdiction_code, coalesce(hub, ''), gate) do update set status = excluded.status, label = excluded.label, note = excluded.note,`
    + ` source_url = excluded.source_url, verified_on = excluded.verified_on, next_check_on = excluded.next_check_on, needs_verification = excluded.needs_verification;`);
}

// ── wealth ───────────────────────────────────────────────────────────────────
const WEALTH_COLS = ['millionaires', 'uhnwi_count', 'business_owners', 'private_wealth_usd_bn', 'trusts_count', 'private_companies_count'];
// Annual averages (employers) are "as at" mid-year; stock counts (millionaires, UHNWI, trusts...) at year end.
const refDate = (year, col, given) => given ?? (col === 'business_owners' ? `${year}-06-30` : `${year}-12-31`);
const wealthRows = [];
for (const w of run.wealth ?? []) {
  if (w.values) for (const [j, v] of Object.entries(w.values)) wealthRows.push({ ...w, j, col: w.column, value: v });
  else for (const col of WEALTH_COLS) if (w[col] !== undefined) wealthRows.push({ ...w, col, value: w[col] });
}
for (const w of wealthRows) {
  if (!WEALTH_COLS.includes(w.col)) { errors.push(`wealth ${w.j}: unknown column ${w.col}`); continue; }
  const url = w.source_url ?? src(w);
  out.push(`-- wealth ${w.j} ${w.year} ${w.col} ← ${w.recipe}`);
  out.push(`insert into wealth_market (jurisdiction_code, year, source, source_url, verified_on, ref_date, ${w.col})`
    + ` values (${q(w.j)}, ${w.year}, ${q(w.source)}, ${q(url)}, ${q(w.verified_on ?? day)}, ${q(refDate(w.year, w.col, w.ref_date))}, ${q(w.value)})`
    + ` on conflict (jurisdiction_code, year, source) do update set ${w.col} = excluded.${w.col}, source_url = excluded.source_url,`
    + ` verified_on = excluded.verified_on, ref_date = excluded.ref_date;`);
}

// ── gaps (what is missing or blocked, and where to get it) ───────────────────
for (const g of run.gaps ?? []) {
  out.push(`-- gap ${g.j} ${g.item}`);
  out.push(`insert into research_item (jurisdiction_code, item, status, detail, where_to_get, checked_on)`
    + ` values (${q(g.j)}, ${q(g.item)}, ${q(g.status)}, ${q(g.detail)}, ${q(g.where_to_get)}, ${q(day)})`
    + ` on conflict (jurisdiction_code, item) do update set status = excluded.status, detail = excluded.detail,`
    + ` where_to_get = excluded.where_to_get, checked_on = excluded.checked_on;`);
}
out.push('', 'reset search_path;', '');
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }

mkdirSync(join(here, '..', 'db', 'research'), { recursive: true });
const target = join(here, '..', 'db', 'research', basename(file).replace(/\.json$/, '.sql'));
writeFileSync(target, out.join('\n'));
console.log(`wrote ${target}: ${js.length} jurisdictions, ${(run.rates ?? []).length} rates, ${(run.treaties ?? []).length} treaties, ${(run.gates ?? []).length} gates, ${wealthRows.length} wealth values, ${(run.gaps ?? []).length} gaps (mode ${mode})`);
