// Turn a research run (research/runs/<date>.json) into idempotent SQL:
//   node research/apply-run.mjs research/runs/2026-09-30.json   → db/research/2026-09-30.sql
//   bash db/apply.sh db/research/2026-09-30.sql
// Rules (research/README.md):
//   mode "history" (default): a changed headline/min/max closes the current row (valid_to = run
//     date) and inserts a new one; an unchanged value only refreshes verification fields.
//   mode "correct": replaces draft rows in place (used once, for the first pass over the seed).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const file = process.argv[2];
if (!file) { console.error('usage: node research/apply-run.mjs research/runs/<date>.json'); process.exit(2); }
const run = JSON.parse(readFileSync(file, 'utf8'));
const recipes = Object.fromEntries(JSON.parse(readFileSync(join(here, 'recipes.json'), 'utf8')).recipes.map((r) => [r.id, r]));
const mode = run.mode === 'correct' ? 'correct' : 'history';
const day = run.run;

const q = (v) => (v === undefined || v === null ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const pick = (map, j) => map[j] ?? map[j.split('-')[0]] ?? map['*'];
const errors = [];
const src = (x) => {
  const r = recipes[x.recipe];
  if (!r) errors.push(`unknown recipe ${x.recipe} (${x.j ?? x.a}:${x.t ?? x.b})`);
  return x.source_override ?? r?.url ?? null;
};

const out = [`-- GENERATED by research/apply-run.mjs from ${basename(file)} (mode: ${mode}) — do not edit.`,
  `-- Every value traces to a recipe in research/recipes.json.`, 'set search_path = offshore_insights;', ''];

for (const x of run.rates) {
  const vf = pick(run.defaults.valid_from, x.j), nc = pick(run.defaults.next_check_on, x.j);
  const min = x.min ?? x.h, max = x.max ?? x.h;
  const cols = { headline_rate: x.h, rate_min: min, rate_max: max, threshold_amount: x.thr, threshold_note: x.thr_note, note: x.note,
    source_url: src(x), verified_on: day, next_check_on: nc, needs_verification: !!x.nv };
  out.push(`-- ${x.j} ${x.t} ← ${x.recipe}`);
  if (mode === 'history') {
    out.push(`update tax_rate set valid_to = ${q(day)} where jurisdiction_code = ${q(x.j)} and tax_type_code = ${q(x.t)} and valid_to is null`
      + ` and (headline_rate is distinct from ${q(x.h)} or rate_min is distinct from ${q(min)} or rate_max is distinct from ${q(max)});`);
  }
  const names = Object.keys(cols);
  out.push(`insert into tax_rate (jurisdiction_code, tax_type_code, valid_from, ${names.join(', ')})`
    + ` values (${q(x.j)}, ${q(x.t)}, ${q(mode === 'history' ? day : vf)}, ${names.map((k) => (k === 'needs_verification' ? String(cols[k]) : q(cols[k]))).join(', ')})`
    + ` on conflict (jurisdiction_code, tax_type_code) where valid_to is null do update set `
    + names.map((k) => `${k} = excluded.${k}`).join(', ') + (mode === 'correct' ? ', valid_from = excluded.valid_from' : '') + ';');
}
out.push('');
for (const t of run.treaties ?? []) {
  const set = ['status = excluded.status', 'mli_note = coalesce(excluded.mli_note, treaty.mli_note)', 'source_url = excluded.source_url',
    'verified_on = excluded.verified_on', 'next_check_on = excluded.next_check_on',
    'wht_dividend = coalesce(excluded.wht_dividend, treaty.wht_dividend)', 'wht_interest = coalesce(excluded.wht_interest, treaty.wht_interest)'];
  out.push(`-- treaty ${t.a}-${t.b} ← ${t.recipe}`);
  out.push(`insert into treaty (country_a, country_b, status, mli_note, wht_dividend, wht_interest, source_url, verified_on, next_check_on)`
    + ` values (${q(t.a)}, ${q(t.b)}, ${q(t.status)}, ${q(t.note)}, ${q(t.wht_dividend)}, ${q(t.wht_interest)}, ${q(src(t))}, ${q(day)}, ${q(t.next_check ?? '2027-03-31')})`
    + ` on conflict (country_a, country_b) do update set ${set.join(', ')};`);
}
out.push('', 'reset search_path;', '');
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }

mkdirSync(join(here, '..', 'db', 'research'), { recursive: true });
const target = join(here, '..', 'db', 'research', basename(file).replace(/\.json$/, '.sql'));
writeFileSync(target, out.join('\n'));
console.log(`wrote ${target}: ${run.rates.length} rates, ${(run.treaties ?? []).length} treaties (mode ${mode})`);
