// Audit a country (and its regions), or everything, against the one checklist (research/checklist.mjs).
//   node research/audit-country.mjs BE            # Belgium + Flanders, Brussels, Wallonia
//   node research/audit-country.mjs all           # every jurisdiction, hubs included
//   node research/audit-country.mjs BE --sql      # also write db/research/audit-<date>-BE.sql (research_item upserts)
//   node research/audit-country.mjs BE --fixture apps/web/.fixture.json   # offline: read a saved dashboard payload
// Reads the same dashboard() payload the page uses, with the service-role key from .env. Prints what is
// missing, stale or blocked and where to get each. Applying the SQL is a separate step (db/apply.sh), after review.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildChecklist, checklistSql, taxYear } from './checklist.mjs';
import { loadDashboard } from './lib.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const flag = (n) => args.includes(n);
const opt = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : null; };
const target = args.find((a) => !a.startsWith('--') && a !== opt('--fixture') && a !== opt('--today'));
if (!target) { console.error('usage: node research/audit-country.mjs <CODE|all> [--sql] [--fixture file] [--today yyyy-mm-dd]'); process.exit(2); }
const today = opt('--today') ?? new Date().toISOString().slice(0, 10);

const loadPayload = async () => (opt('--fixture') ? JSON.parse(readFileSync(opt('--fixture'), 'utf8')) : loadDashboard());

const d = await loadPayload();
const recipes = JSON.parse(readFileSync(join(here, 'recipes.json'), 'utf8')).recipes;
d.research_items ??= []; d.advisors ??= []; d.treaties ??= []; d.gates ??= []; d.wealth ??= []; d.rate_history ??= [];
const all = buildChecklist(d, today, { recipes });

const codes = target === 'all' ? d.jurisdictions.map((j) => j.code)
  : d.jurisdictions.filter((j) => j.code === target || j.parent_code === target).map((j) => j.code);
if (!codes.length) { console.error(`no jurisdiction ${target}`); process.exit(1); }
const items = all.filter((i) => codes.includes(i.jurisdiction_code));

const mark = { have: '  ok ', missing: 'MISS ', blocked: 'BLOCK', stale: 'STALE' };
let bad = 0;
for (const c of codes) {
  const j = d.jurisdictions.find((x) => x.code === c);
  const mine = items.filter((i) => i.jurisdiction_code === c);
  const ty = taxYear(j.tax_year_start ?? d.jurisdictions.find((x) => x.code === j.parent_code)?.tax_year_start, today);
  const have = mine.filter((i) => i.status === 'have').length;
  console.log(`\n${j.name} (${c}${j.parent_code ? ', region of ' + j.parent_code : ''}) · tax year ${ty.label} (${ty.start} to ${ty.end}) · ${have} of ${mine.length} items in place`);
  for (const i of mine.filter((x) => x.status !== 'have')) {
    bad++;
    console.log(`  ${mark[i.status]} ${i.item}${i.detail ? ' · ' + i.detail : ''}${i.where_to_get ? '\n          → ' + i.where_to_get : ''}`);
  }
  if (have === mine.length) console.log('  everything on the checklist is in place');
}
console.log(`\n${bad} open item${bad === 1 ? '' : 's'} across ${codes.length} jurisdiction${codes.length === 1 ? '' : 's'} (checked ${today}).`);

if (flag('--sql')) {
  mkdirSync(join(here, '..', 'db', 'research'), { recursive: true });
  const out = join(here, '..', 'db', 'research', `audit-${today}-${target}.sql`);
  writeFileSync(out, `-- GENERATED by research/audit-country.mjs (${target}, ${today}) — do not edit.\n` + checklistSql(items, today, codes));
  console.log(`wrote ${out}`);
}
