// Recipe "ilo-employers" (method: api), run locally without n8n:
//   node research/fetch-ilo.mjs   → db/research/ilo-<date>.sql   (then: bash db/apply.sh <file>)
// Business owners for the countries Eurostat does not cover (UK, South Africa): employers
// (ICSE-93 status 2, "self-employed with employees") from each country's labour force survey,
// via the ILO SDMX API. Same definition as Eurostat lfsa_egaps SELF_S: checked 2026-09-30,
// France 2024 ILO 1,382k vs Eurostat 1,375k; Germany 2025 1,753k vs 1,715k.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const today = new Date().toISOString().slice(0, 10);
const COUNTRIES = { GB: 'GBR', ZA: 'ZAF' };          // ISO2 (ours) → ISO3 (ILO)
const FROM = 2020;
const SOURCE = 'ILOSTAT employers (labour force survey, ICSE-93)';

const rows = [];
for (const [code, iso3] of Object.entries(COUNTRIES)) {
  const url = `https://sdmx.ilo.org/rest/data/ILO,DF_EMP_TEMP_SEX_STE_NB,1.0/${iso3}.A..SEX_T.STE_ICSE93_2?startPeriod=${FROM}&format=csv`;
  let res;
  for (let attempt = 1; attempt <= 3; attempt++) {           // and retry the odd transient 500
    // Accept-Language must be explicit: Node's default '*' makes the ILO server answer 500.
    res = await fetch(url, { headers: { 'User-Agent': 'Off_Shore_Insights research', 'Accept-Language': 'en' } });
    if (res.ok || res.status < 500) break;
    await new Promise((r) => setTimeout(r, 3000 * attempt));
  }
  if (!res.ok) throw new Error(`ILO ${iso3} ${res.status}`);
  const [head, ...lines] = (await res.text()).trim().split(/\r?\n/);
  const col = (n) => head.split(',').indexOf(n);
  const iYear = col('TIME_PERIOD'), iVal = col('OBS_VALUE'), iStatus = col('OBS_STATUS');
  if (iYear < 0 || iVal < 0) throw new Error(`ILO ${iso3}: unexpected columns ${head}`);
  for (const l of lines) {
    const f = l.split(',');
    const v = Number(f[iVal]);
    if (!Number.isFinite(v) || f[iStatus] === 'U') continue;   // U = unreliable
    rows.push({ code, year: Number(f[iYear]), value: Math.round(v * 1000), url });   // thousands → people
  }
}
if (!rows.length) throw new Error('ILO returned no rows');

const q = (v) => (typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const sql = ['-- GENERATED by research/fetch-ilo.mjs (recipe ilo-employers). Do not edit.', 'set search_path = offshore_insights;',
  ...rows.map((r) => `insert into wealth_market (jurisdiction_code, year, business_owners, source, source_url, verified_on) values (${[r.code, r.year, r.value, SOURCE, r.url, today].map(q).join(', ')}) on conflict (jurisdiction_code, year, source) do update set business_owners = excluded.business_owners, source_url = excluded.source_url, verified_on = excluded.verified_on;`),
  'reset search_path;', ''];
mkdirSync(join(here, '..', 'db', 'research'), { recursive: true });
const out = join(here, '..', 'db', 'research', `ilo-${today}.sql`);
writeFileSync(out, sql.join('\n'));
console.log(`wrote ${out}: ${rows.length} rows`);
for (const r of rows) console.log(`  ${r.code} ${r.year} ${r.value.toLocaleString('en')}`);
