// Recipe "fx-eur" (method: api): exchange rates to convert local-currency thresholds to EUR.
//   node research/fetch-fx.mjs   → db/research/fx-<date>.sql   (then: bash db/apply.sh <file>)
// Source: open.er-api.com (free, no key; daily). Covers MUR and SCR, which the ECB does not.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadDashboard } from './lib.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const URL_ = 'https://open.er-api.com/v6/latest/EUR';
// Every currency a jurisdiction uses (plus EUR, and USD: the report's principal and the index are in US dollars), read from the database so a new country needs no edit here.
const CURRENCIES = [...new Set(['EUR', 'USD', ...(await loadDashboard()).jurisdictions.map((j) => j.currency)])].sort();

const j = await (await fetch(URL_)).json();
if (j.result !== 'success') throw new Error('FX API: ' + JSON.stringify(j).slice(0, 200));
const asOf = new Date(j.time_last_update_unix * 1000).toISOString().slice(0, 10);
const rows = CURRENCIES.map((c) => {
  const perEur = j.rates[c];
  if (!(perEur > 0)) throw new Error(`no rate for ${c}`);
  return { c, eur: 1 / perEur };
});
const sql = ['-- GENERATED by research/fetch-fx.mjs (recipe fx-eur) — do not edit.', 'set search_path = offshore_insights;',
  ...rows.map((r) => `insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('${r.c}', ${r.eur.toFixed(8)}, '${asOf}', '${URL_}') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;`),
  'reset search_path;', ''];
mkdirSync(join(here, '..', 'db', 'research'), { recursive: true });
const out = join(here, '..', 'db', 'research', `fx-${asOf}.sql`);
writeFileSync(out, sql.join('\n'));
console.log(`wrote ${out}: ${rows.map((r) => `${r.c}=${r.eur.toFixed(5)}€`).join(' ')}`);
