// The ECB euro foreign exchange reference rate at the END of each calendar year, per currency: what a report converts the allowances of THAT year at.
// (fx_rate holds only today's rate, which misstates an allowance over a ten-year history.) Pure functions; research/fetch-fx-years.mjs does the fetching.
// A year whose last published rate is not from the last days of that year is MISSING, never filled from another year: unknown stays unknown.
import { lastOnOrBefore } from './index-currency.mjs';

/** The currencies a report can need that the ECB publishes: the report currencies (USD, ZAR) and the home currencies (GBP, CHF, ZAR). EUR is 1. MUR and SCR are not published by the ECB; no hub allowance needs them today. */
export const FX_CURRENCIES = ['USD', 'GBP', 'CHF', 'ZAR'];
export const ecbUrl = (currency) => `https://data-api.ecb.europa.eu/service/data/EXR/D.${currency}.EUR.SP00.A`;

/**
 * Year-end rates from parsed ECB observations ({ USD: [{date, value}], ... }; value = units of currency per 1 EUR).
 * A rate counts as the year's end only if it was published on or after 20 December of that year (the ECB's last fixing is always within days of 31 December).
 */
export function yearEndRates(obs, currencies, years) {
  const rows = [], missing = [];
  for (const currency of currencies) for (const year of years) {
    const o = lastOnOrBefore(obs[currency] ?? [], `${year}-12-31`);
    if (!o || o.date < `${year}-12-20`) { missing.push({ currency, year }); continue; }
    rows.push({ currency, year, date: o.date, perEur: o.value, eurPerUnit: Math.round((1 / o.value) * 1e8) / 1e8 });
  }
  return { rows, missing };
}

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
/** Idempotent SQL for the rows (apply with bash db/apply.sh). */
export function fxYearSql(rows, { today }) {
  const out = ['-- GENERATED by research/fetch-fx-years.mjs (recipe ecb-fx-year-end) — do not edit.', 'set search_path = offshore_insights;', ''];
  for (const r of rows) {
    out.push(`-- ${r.currency} ${r.year} ← ECB ${r.date}: 1 EUR = ${r.perEur} ${r.currency}`);
    out.push(`insert into fx_rate_year (currency, year, eur_per_unit, source, source_url, verified_on) values (${q(r.currency)}, ${r.year}, ${r.eurPerUnit}, `
      + `${q(`ECB euro foreign exchange reference rate of ${r.date}: 1 EUR = ${r.perEur} ${r.currency}`)}, ${q(ecbUrl(r.currency))}, ${q(today)})`
      + ` on conflict (currency, year) do update set eur_per_unit = excluded.eur_per_unit, source = excluded.source, source_url = excluded.source_url, verified_on = excluded.verified_on;`);
  }
  out.push('', 'reset search_path;', '');
  return out.join('\n');
}

/** Stored year-end rates (dashboard().fx_history) that the new rows would CHANGE: the old value is replaced by the newest edition, and Hentus is shown it first. */
export function restatedFx(rows, stored = []) {
  return rows.flatMap((r) => {
    const old = stored.find((s) => s.currency === r.currency && s.year === r.year);
    return old && Math.abs(Number(old.eur_per_unit) - r.eurPerUnit) > 1e-8 ? [{ currency: r.currency, year: r.year, old: Number(old.eur_per_unit), now: r.eurPerUnit, oldSource: old.source, newSource: `ECB ${r.date}` }] : [];
  });
}
