// Source of truth for HOW each figure is retrieved. Regenerates recipes.json:
//   node research/recipes.mjs
// method: 'api' → n8n (no AI) · 'page-extract' → /update-offshore-insights skill · 'manual' → human.
import { writeFileSync } from 'node:fs';

const P = (slug, page) => `https://taxsummaries.pwc.com/${slug}/${page}`;
const OTHER = ['INHERITANCE_DIRECT', 'INHERITANCE_OTHER', 'WEALTH_NET', 'WEALTH_SOLIDARITY', 'WEALTH_PROPERTY', 'SECURITIES_ACCOUNT', 'FOREIGN_ASSET_TAX', 'FOREIGN_PROPERTY'];

const pwc = (code, slug) => [
  { id: `pwc-${code}-pit`, method: 'page-extract', url: P(slug, 'individual/taxes-on-personal-income'), cells: [`${code}:INCOME_TOP`],
    extract: 'Top marginal personal income tax rate for residents, its threshold, and surcharges on top (solidarity, high-income, regional/municipal ranges). Tax year.' },
  { id: `pwc-${code}-cg`, method: 'page-extract', url: P(slug, 'individual/income-determination'), cells: [`${code}:CGT_FINANCIAL`, `${code}:CGT_PROPERTY`],
    extract: 'Capital gains of resident individuals: shares/funds (rate, annual exemption) and real estate (rate, holding-period relief, main-home exemption).' },
  { id: `pwc-${code}-other`, method: 'page-extract', url: P(slug, 'individual/other-taxes'), cells: OTHER.map((t) => `${code}:${t}`),
    extract: 'Inheritance/gift tax (top rate + allowance for children; top rate for unrelated heirs). Net wealth, large-fortune/solidarity, real-estate wealth, securities-account, foreign-asset and foreign-real-estate taxes (rate, threshold). Stated as non-existent = 0. Not mentioned at all = 0 with note "none listed in PwC Other taxes".' },
  { id: `pwc-${code}-wht`, method: 'page-extract', url: P(slug, 'corporate/withholding-taxes'), cells: [`${code}:WHT_DIVIDEND`, `${code}:WHT_INTEREST`],
    extract: 'Domestic withholding tax on dividends and on interest paid to NON-RESIDENT INDIVIDUALS: standard rate, higher rate for blacklisted/non-cooperative jurisdictions, main exceptions.' },
];

const recipes = [
  ...pwc('FR', 'france'), ...pwc('DE', 'germany'), ...pwc('BE', 'belgium'), ...pwc('GB', 'united-kingdom'), ...pwc('IT', 'italy'),
  ...pwc('ES', 'spain'), ...pwc('ZA', 'south-africa'), ...pwc('PT', 'portugal'), ...pwc('CH', 'switzerland'), ...pwc('NL', 'netherlands'), ...pwc('LU', 'luxembourg'),
  { id: 'pwc-MU-pit', method: 'page-extract', url: P('mauritius', 'individual/taxes-on-personal-income'), cells: ['MU:INCOME_TOP'],
    extract: 'Resident income tax bands and top rate; Fair Share Contribution rate, threshold and the income years it applies to.' },
  { id: 'pwc-MU-other', method: 'page-extract', url: P('mauritius', 'individual/other-taxes'), cells: OTHER.map((t) => `MU:${t}`),
    extract: 'Whether Mauritius levies inheritance, estate, gift or net wealth taxes (quote the "there are no ..." sentences).' },
  { id: 'pwc-MU-cg', method: 'page-extract', url: P('mauritius', 'corporate/income-determination'), cells: ['MU:CGT_FINANCIAL'],
    extract: 'The sentence on capital gains tax in Mauritius and its exception.' },
  { id: 'pwc-MU-property', method: 'page-extract', url: P('mauritius', 'corporate/other-taxes'), cells: ['MU:CGT_PROPERTY'],
    extract: 'Land transfer tax (rate, who pays, changes for non-citizens) and registration duty on immovable property.' },
  { id: 'pwc-MU-wht', method: 'page-extract', url: P('mauritius', 'corporate/withholding-taxes'), cells: ['MU:WHT_DIVIDEND', 'MU:WHT_INTEREST', 'treaty:MU-*:wht'],
    extract: 'Domestic WHT on dividends and interest (residents / non-residents) and the treaty table (dividends / interest) for BE, FR, DE, IT, ZA, GB, SC.' },
  { id: 'src-SC-income', method: 'page-extract', url: 'https://src.gov.sc/income-and-non-monetary-benefits-tax/', cells: ['SC:INCOME_TOP'],
    extract: 'Monthly income tax bands on emoluments for citizens and non-citizens; top rate and threshold.' },
  { id: 'src-SC-system', method: 'page-extract', url: 'https://src.gov.sc/seychelles-tax-system/',
    cells: ['SC:WHT_DIVIDEND', 'SC:WHT_INTEREST', 'SC:WEALTH_PROPERTY', 'SC:CGT_FINANCIAL', 'SC:WEALTH_NET', 'SC:WEALTH_SOLIDARITY', 'SC:SECURITIES_ACCOUNT', 'SC:FOREIGN_ASSET_TAX', 'SC:FOREIGN_PROPERTY'],
    extract: 'Every rate listed: WHT to non-residents (dividends, interest, bank-interest exceptions), Immovable Property Tax. Taxes NOT listed (CGT, inheritance, gift, wealth) stay needs_verification until an official statement confirms they do not exist.' },
  { id: 'sib-SC-taxes', method: 'page-extract', url: 'https://investinseychelles.com/investors-guide/investor-resources/seychelles-tax-guide',
    alt_urls: ['http://www.sib.gov.sc/index.php/investment-guide/investors-guide/taxes'],
    cells: ['SC:CGT_FINANCIAL', 'SC:WEALTH_NET', 'SC:WEALTH_SOLIDARITY', 'SC:SECURITIES_ACCOUNT'],
    extract: 'Seychelles Investment Board tax guide (sib.gov.sc until 2018, investinseychelles.com since 2021): the taxes it lists as administered by the SRC. A tax not listed stays needs_verification, as for src-SC-system. Back years: dated Wayback copies only.' },
  { id: 'chambers-SC-realestate', method: 'page-extract', url: 'https://practiceguides.chambers.com/practice-guides/real-estate-2026/seychelles', cells: ['SC:CGT_PROPERTY'],
    extract: 'Stamp duty and fees when a non-Seychellois buys immovable property; any capital gains tax on sale.' },
  { id: 'secondary-SC-death-taxes', method: 'page-extract', url: 'https://www.expanship.com/sc/blog/seychelles-inheritance-and-estate-tax', cells: ['SC:INHERITANCE_DIRECT', 'SC:INHERITANCE_OTHER'],
    extract: 'Whether Seychelles levies inheritance/estate tax. Secondary source: keep needs_verification = true.' },
  { id: 'law-DE-erbstg', method: 'page-extract', url: 'https://www.gesetze-im-internet.de/erbstg_1974/__19.html', cells: ['DE:INHERITANCE_DIRECT', 'DE:INHERITANCE_OTHER'],
    extract: 'The full §19(1) ErbStG rate table, every row for classes I–III (do not summarise). Allowances from §16: https://www.gesetze-im-internet.de/erbstg_1974/__16.html.' },
  { id: 'gov-GB-cgt', method: 'page-extract', url: 'https://www.gov.uk/capital-gains-tax/rates', cells: ['GB:CGT_FINANCIAL', 'GB:CGT_PROPERTY'],
    extract: 'CGT rates for basic and higher/additional-rate taxpayers for the current tax year; annual exempt amount from https://www.gov.uk/capital-gains-tax/allowances.' },
  { id: 'pwcnews-BE-cgt', method: 'page-extract', url: 'https://news.pwc.be/belgiums-comprehensive-capital-gains-tax-changes-key-updates-and-implications-starting-january-2026/', cells: ['BE:CGT_FINANCIAL'],
    extract: 'The 2026 Belgian capital gains tax on financial assets: rate, exemption, internal-gains rate, law date and publication. (The PwC WWTS individual page was still outdated on 2026-09-30.)' },
  { id: 'region-BE-inheritance', method: 'page-extract', url: 'https://www.vlaanderen.be/belastingen-en-begroting/vlaamse-belastingen/erfbelasting',
    alt_urls: ['https://fiscalite.brussels/', 'https://finances.wallonie.be/'],
    cells: ['BE-VLG', 'BE-BRU', 'BE-WAL'].flatMap((r) => [`${r}:INHERITANCE_DIRECT`, `${r}:INHERITANCE_OTHER`]),
    extract: 'Official regional inheritance tariffs: direct line lowest/highest, unrelated lowest/highest, upcoming reforms (Wallonia 2028). The 2026-09-30 run used secondary sources (pia.be, Expatica): replace them and clear needs_verification.' },
  { id: 'mra-MU-dta', method: 'page-extract', url: 'https://www.mra.mu/taxes-duties/international-taxation/double-taxation-agreements', cells: ['treaty:MU-*:status'],
    extract: 'Per target country: in force / awaiting signature / awaiting ratification / under negotiation / not listed (= none). Dates are in the treaty PDFs linked from the page.' },
  { id: 'src-SC-dta', method: 'page-extract', url: 'https://src.gov.sc/agreements/', cells: ['treaty:SC-*:status'],
    extract: 'Which target countries have a DTA with Seychelles. Listed = agreement exists (confirm in-force date from the treaty text); not listed = none.' },
  // ── Back years (2015 onward) for the four taxes the ten-year report reads ──
  { id: 'deloitte-highlights', method: 'page-extract', url: 'https://www2.deloitte.com/content/dam/Deloitte/global/Documents/Tax/dttl-tax-<country>highlights-<YEAR>.pdf',
    cells: ['*:CGT_FINANCIAL', '*:WEALTH_NET', '*:WEALTH_SOLIDARITY'],
    extract: 'Deloitte International Tax "<Country> Highlights <YEAR>" (one dated edition a year, as at January): the lines "Capital gains", "Net wealth/net worth tax", "Inheritance/estate tax". Older editions only through dated Wayback copies (pdftotext -layout). An edition is evidence for the tax year it falls in, never for an earlier or later one.' },
  { id: 'ey-personal-tax-guide', method: 'page-extract', url: 'https://www.ey.com/en_gl/tax-guides',
    cells: ['*:CGT_FINANCIAL', '*:WEALTH_NET', '*:WEALTH_SOLIDARITY', '*:SECURITIES_ACCOUNT'],
    extract: 'EY Worldwide Personal Tax (and Immigration) Guide, one edition a year, "content current on 1 July <YEAR>" (editions 2015-16 to 2019-20 are in the Wayback Machine under www.ey.com/Publication/vwLUAssets/...). The country chapter: "Capital gains" under A. Income tax, and "B. Other taxes" (net worth tax, estate and gift taxes). An edition is evidence for the tax year that contains 1 July of its first year. Read with pdftotext -layout.' },
  { id: 'nl-bd-box3-history', method: 'page-extract', url: 'https://www.belastingdienst.nl/wps/wcm/connect/fisin/fisin2019/belastingberekening',
    alt_urls: ['https://www.belastingdienst.nl/wps/wcm/connect/nl/box-3/content/berekening-box-3-inkomen-2021'],
    cells: ['NL:WEALTH_NET'],
    extract: 'Box 3 for a past year from the Belastingdienst\'s own year pages: fisin<YEAR>/belastingberekening (2019 onward, section "Box 3: inkomen uit sparen en beleggen": heffingsvrij vermogen, the 2 percentages, the 3 schijven with their savings/investments mix, the tax rate), berekening-box-3-inkomen-<YEAR> (2021 onward, newer: the method on actual holdings), and for 2015-2018 the dated Wayback copies of the pages "berekenen belasting over vermogen tot en met 2016", "berekening 2017", "berekening 2018" and the heffingsvrij-vermogen pages. Effective rate = tax rate x deemed return (derived: say so).' },
  { id: 'es-aeat-patrimonio', method: 'page-extract', url: 'https://sede.agenciatributaria.gob.es/static_files/Sede/Biblioteca/Manual/Practicos/Patrimonio/Patrimonio-<YEAR>/ManualPatrimonio<YEAR>_es_es.pdf',
    alt_urls: ['https://sede.agenciatributaria.gob.es/static_files/Sede/Biblioteca/Manual/Practicos/IRPF/IRPF-<YEAR>/ManualRentaPatrimonio<YEAR>_es_es.pdf (2016-2017)', 'IRPF-2019/ManualRenta2019_es_es.pdf', 'Wayback: ManualRentaPatrimonio2018_V8_es_es.pdf, Addenda_CCAA_IP_2015.pdf', 'https://www.hacienda.gob.es/SGFAL/FinanciacionTerritorial/autonomica/ (Tributación Autonómica. Medidas <YEAR>)'],
    cells: ['ES-*:WEALTH_NET'],
    extract: 'Spanish wealth tax per autonomous community for the year, from the yearly manual of the tax agency: (1) "mínimo exento" list (default 700,000), (2) "Escalas autonómicas" (state scale when a region has none: top 2.5% to 2020, 3.5% from 2021), (3) "Bonificaciones autonómicas" (general rebates; from 2023 several regions replace a 100% rebate by "wealth tax minus ITSGF" while the ITSGF applies, which leaves only the ITSGF to pay: store 0). Store headline = top band x (1 - general rebate), min = lowest band likewise, threshold = mínimo exento.' },
  { id: 'es-reaf-panorama', method: 'page-extract', url: 'https://economistas.es/Contenido/REAF/Informes/Panorama<YEAR>.pdf',
    alt_urls: ['Wayback copies of the 2016 to 2022 editions under economistas.es/Contenido/... and reaf.economistas.es'],
    cells: ['ES-VI:*', 'ES-BI:*', 'ES-SS:*', 'ES-NC:*'],
    extract: 'REAF (Consejo General de Economistas) "Panorama de la Fiscalidad Autonómica y Foral <YEAR>": one edition a year describing that year. For the foral territories (Álava, Bizkaia, Gipuzkoa, Navarra): wealth tax mínimo exento and scale (summary "En los territorios del País Vasco existe un Impuesto sobre la Riqueza..." and the Navarra chapter 17.2), savings scale ("Tarifa del ahorro"), and the Basque solidarity tax (chapter 16.5, from 2023). A compiled series: the own guides of the foral treasuries win where held.' },
  { id: 'estv-taxburden', method: 'api', url: 'https://swisstaxcalculator.estv.admin.ch/#/taxburden/income-wealth-tax',
    cells: ['CH-*:WEALTH_NET'],
    automation: 'POST https://swisstaxcalculator.estv.admin.ch/delegate/ost-integration/v1/export/income-tax-values/JSON/DE with {massExportModelId:1 (single, no children), belastungsVergleich:1, taxGroup:88 (canton capitals), confession:5 (no church tax), incomes:[], fortunes:[...], klasse:2 (wealth), years:[...], output:1 (tax in CHF)} and headers Origin/Referer of the calculator. Returns the wealth tax (canton + commune) in each canton capital for each net wealth and year.',
    extract: 'Per canton and tax year: top marginal rate = (tax on CHF 51m - tax on CHF 50m) / CHF 1m; lowest band = slope just above the taxed-from amount; taxed-from amount = the last net wealth (to CHF 1,000) with no tax beyond the flat personal tax. Also the tax on CHF 1m and 10m for the note.' },
  { id: 'lu-guichet-succession', method: 'page-extract', url: 'https://guichet.public.lu/fr/citoyens/sante/fin-vie/deces/droits-succession-heritage.html', cells: ['LU:INHERITANCE_DIRECT', 'LU:INHERITANCE_OTHER'],
    extract: 'Luxembourg state portal: inheritance base rates by relationship (direct line 0% on the legal share, 2.5% / 5% beyond it; spouses; siblings 6%; others 15%) and the surcharge ("majoration") by the value of the share. Back years: dated Wayback copies.' },
  { id: 'be-fin-pit', method: 'page-extract', url: 'https://fin.belgium.be/nl/particulieren/belastingaangifte/belastingtarieven-inkomen/belastingtarieven', cells: ['BE:INCOME_TOP'],
    extract: 'FOD Financien: the federal income tax brackets (25% to 50%) for the last two income years shown side by side; the 50% band starts at the top limit of the 45% band. Older years: dated Wayback copies (each copy shows two income years). The municipal surcharge (0% to 9% of the tax) is on top.' },
  { id: 'pt-cimi-aimi', method: 'page-extract', url: 'https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cimi/Pages/cimi135f.aspx', cells: ['PT:WEALTH_PROPERTY'],
    extract: 'AIMI (adicional ao IMI), Portal das Financas copy of the IMI code: art. 135-F rates for individuals (0.7%; 1% on the part of the taxable value above EUR 1m up to 2m; 1.5% above 2m) and art. 135-C (.../cimi135c.aspx) the EUR 600,000 deduction for an individual. Back years: dated Wayback copies.' },
  { id: 'lu-nc-list', method: 'page-extract', url: 'https://impotsdirects.public.lu/fr/az/l/ListeUEterritoiresNC.html', cells: ['gate:LU:blacklist:MU', 'gate:LU:blacklist:SC'],
    extract: 'The copy kept by the Luxembourg tax administration of the EU list of non-cooperative jurisdictions applied under art. 168 L.I.R. (law of 10 Feb 2021), with every version and its dates. Are Mauritius / Seychelles named in the version in force, and in which earlier versions?' },
  // ── Gates (jurisdiction_gate) ──
  { id: 'eu-annex-i', method: 'page-extract', url: 'https://taxation-customs.ec.europa.eu/taxation/common-eu-list-third-country-jurisdictions-tax-purposes_en',
    alt_urls: ['https://taxation-customs.ec.europa.eu/news/eu-updates-list-non-cooperative-tax-jurisdictions-highlighting-commitment-global-tax-good-governance-2026-02-17_en'],
    cells: ['gate:DE:blacklist:*'], extract: 'Current Annex I (non-cooperative) and Annex II (state of play) lists and their date. Are Mauritius / Seychelles on either? Germany applies Annex I (StAbwG).' },
  { id: 'fr-etnc', method: 'page-extract', url: 'https://kpmg.com/av/fr/avocats/eclairages/2026/06/publication-de-l-arrete-annuel-2026-fixant-la-liste-noire-francaise-des-etnc.html',
    cells: ['gate:FR:blacklist:*'], extract: 'The French ETNC list from the latest annual arrêté (JO date). Are Maurice / Seychelles listed or removed (and when)? Prefer the Légifrance arrêté text when available.' },
  { id: 'es-no-cooperativas', method: 'page-extract', url: 'https://sede.agenciatributaria.gob.es/Sede/ayuda/manuales-videos-folletos/manuales-practicos/manual-tributacion-no-residentes/anexos/jurisdicciones-no-cooperativas.html',
    cells: ['gate:ES:blacklist:*'], extract: "Spain's current non-cooperative jurisdictions (Orden HFP/115/2023 as amended). Mauricio / Seychelles listed? Latest modification and date." },
  { id: 'pt-portaria-150-2004', method: 'page-extract', url: 'https://files.dre.pt/1s/2004/02/037b00/08600860.pdf',
    alt_urls: ['https://diariodarepublica.pt/dr/legislacao-consolidada/portaria/2004-105808897'],
    cells: ['gate:PT:blacklist:*'], extract: 'Portaria 150/2004 list (PDF: read it as a document). Entries for Maurícias and Seychelles, then check the consolidated version / later portarias (2011, 2016, 292/2025) for removals.' },
  { id: 'it-dm-1999', method: 'page-extract', url: 'https://www.agenziaentrate.gov.it/portale/documents/20143/369991/DM+4_5_1999.pdf/fcbaea6a-1cf2-23ec-4a40-9f8f92acdc6e',
    cells: ['gate:IT:blacklist:*'], extract: 'DM 4 May 1999 (privileged-tax states for individuals), as in force: is "Maurizio" / "Seicelle" listed? (PDF: read it as a document.)' },
  { id: 'be-tax-havens', method: 'manual', url: 'https://fin.belgium.be/',
    cells: ['gate:BE:blacklist:*'], extract: "Belgium's yearly Excel of tax-haven lists (art. 179 KB/WIB 92, art. 73/4quater, Global Forum non/partially compliant). Is Mauritius / Seychelles on any? Seychelles was on the reporting list from 2021; its 2026 Global Forum upgrade may have removed it." },
  { id: 'hcch-trusts', method: 'page-extract', url: 'https://www.hcch.net/en/instruments/conventions/status-table/?cid=59',
    cells: ['gate:*:trust_recognition'], extract: 'Hague Trusts Convention (1985) status: parties with entry-into-force date, signatories only. Party = green; signed only = amber; not a party = amber ("recognition depends on domestic law").' },
  { id: 'marketing-rules', method: 'manual', url: '',
    cells: ['gate:*:marketing'], extract: 'Whether cross-border marketing of offshore structures to residents is allowed. No objective public source: Justus decides per country.' },
  { id: 'fx-eur', method: 'api', url: 'https://open.er-api.com/v6/latest/EUR', cells: ['fx_rate'],
    automation: 'node research/fetch-fx.mjs (run by /update-offshore-insights)', extract: 'EUR per unit for EUR, USD, GBP, ZAR, CHF, MUR, SCR. USD is there because the report principal and the index are in US dollars.' },
  { id: 'ecb-fx-year-end', method: 'api', url: 'https://data-api.ecb.europa.eu/service/data/EXR/D.USD+GBP+CHF+ZAR.EUR.SP00.A', cells: ['market_return:MSCI_WORLD:EUR', 'market_return:MSCI_WORLD:ZAR', 'fx_rate_year'],
    automation: 'node research/derive-index-currency.mjs [--with <unapplied msci run>] (then apply-run on the run file it writes); node research/fetch-fx-years.mjs (year-end rates into fx_rate_year, SQL for db/apply.sh)',
    extract: 'ECB euro foreign exchange reference rates (units of currency per 1 EUR), USD, GBP, CHF and ZAR, on the last day published on or before 31 December of each year (a rate from before 20 December is not a year end and is reported missing). Two uses. (1) fx_rate_year: what a report converts the allowances of THAT year at, so a ten-year history never uses the rate of today. (2) Used to DERIVE the euro and rand returns of the MSCI World Index from its US-dollar return: '
      + 'return_C = (1 + return_USD) x (C per USD at the end / C per USD at the start) - 1. The derived rows are labelled DERIVED in their source text, with the rates and dates used; MSCI does not publish them. The page is a CSV API: ?startPeriod=...&endPeriod=...&format=csvdata, Accept: text/csv.' },
  { id: 'msci-world-usd-annual', method: 'page-extract', url: 'https://www.msci.com/documents/10199/178e6643-6ae6-47b9-82be-e1fc565ededb', cells: ['market_return:MSCI_WORLD'],
    extract: 'MSCI World Index (USD) factsheet, table "ANNUAL PERFORMANCE (%)" (columns: MSCI World, MSCI Emerging Markets, MSCI ACWI). Read with pdftotext -raw: the PDF is served as a binary download, so fetch it with curl and keep the file in PDFs/. '
      + 'Take the MSCI World column for every CLOSED calendar year (2024 = 19.19, 2025 = 21.60 in the factsheet dated 31 Aug 2026; the current year is year-to-date and is never stored). BASIS: this factsheet is GROSS returns in USD (before withholding tax on dividends); '
      + 'store basis "gross" and say so on every report. If a NET-return USD factsheet becomes fetchable, store it as a separate basis "net" and prefer it. CURRENCY: USD only, so the report is in US dollars before currency moves; '
      + 'a EUR or GBP series gives very different numbers (a search snippet quoted 26.60 and 6.77 for EUR net: unconfirmed, not used). RIGHTS: MSCI restricts redistribution of its data; confirm permission before the figures appear in a PDF that leaves the firm.' },
  { id: 'eurostat-employers', method: 'api',
    url: 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/lfsa_egaps?format=JSON&lang=EN&wstatus=SELF_S&sex=T&age=Y15-74&unit=THS_PER',
    cells: ['wealth_market.business_owners'], automation: 'node research/fetch-eurostat.mjs (run by /update-offshore-insights); n8n E1 exists but is paused',
    extract: 'JSON-stat: value × 1000 per geo per year.' },
  { id: 'ubs-gwr-millionaires', method: 'manual', url: 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', cells: ['wealth_market.millionaires'],
    extract: 'UBS Global Wealth Report, latest edition (2026 edition published 30 June 2026): USD millionaires per country from the databook PDF (registration required). One row per country and year, source "UBS Global Wealth Report <edition>". '
      + '2026 edition: main report p.21 "The UBS Millionaire Index" (thousands, end 2025) lists 34 markets; extract every one, not only ours (a market missing from the table is not published, never 0). ONE EDITION PER SERIES: UBS restates its history every year (France: 2,897k for end-2024 in the 2025 edition, 2,388k for end-2025 in the 2026 edition; the 2025 table lists only 25 selected markets), so an older edition is not a back year of this series; never mix editions. The upper bands (5-10m, 10-50m, 50-100m) are growth rates only.' },
  // No HNWI recipe: Capgemini (investable assets > US$1m) publishes only global and regional totals and a few markets in prose,
  // Henley's lists are top-20 and not a dataset, and Altrata's free report has no country table (checked 2026-09-30 and 2026-10-02).
  // The US$1m tier is the UBS millionaire count above; the US$30m tier is Knight Frank below.
  { id: 'knightfrank-uhnwi', method: 'manual', url: 'https://www.knightfrank.com/wealthreport', cells: ['wealth_market.uhnwi_count'],
    extract: 'Knight Frank Wealth Report: UHNWI (> US$30m) population per country. '
      + '2026 edition: Databank "Global wealth populations by market" (2021, 2026, 2031f). Read with pdftotext -table (the -layout text shifts rows) and check each row against its % change column. About 50 markets are listed (markets under 500 UHNWIs are not); extract every one. Belgium is not listed. ONE EDITION PER SERIES: the model is revised between editions (Netherlands, 2024 edition: 8,390 for 2023; 2026 edition: 4,493 for 2021 and 5,077 for 2026) and the 2025 edition tabulates a US$10m+ population instead, so older editions are not back years of this series; never mix editions.' },
  { id: 'ilo-employers', method: 'api', url: 'https://sdmx.ilo.org/rest/data/ILO,DF_EMP_TEMP_SEX_STE_NB,1.0/', cells: ['wealth_market.business_owners:GB', 'wealth_market.business_owners:ZA'],
    extract: 'node research/fetch-ilo.mjs. Employers (ICSE-93 status 2) from the national labour force survey via the ILO SDMX API, for the countries Eurostat lacks. Same definition as Eurostat SELF_S (France 2024: 1,382k vs 1,375k). Needs an explicit Accept-Language header.' },
  // ── Netherlands: primary sources (Belastingdienst, wetten.overheid.nl) that win over the PwC pages ──
  { id: 'nl-bd-box1', method: 'page-extract', url: 'https://www.belastingdienst.nl/wps/wcm/connect/nl/werk-en-inkomen/content/hoeveel-inkomstenbelasting-betalen', cells: ['NL:INCOME_TOP'],
    extract: 'Box 1 brackets and percentages for people below AOW age, current year (2026). Earlier years: Belastingdienst fiscal-information pages https://www.belastingdienst.nl/wps/wcm/connect/fisin/fisin<YEAR>/belastingberekening. Top rate and the bracket above which it applies.' },
  { id: 'nl-bd-box2', method: 'page-extract', url: 'https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/box_2/box_2', cells: ['NL:CGT_FINANCIAL'],
    extract: 'Box 2 (substantial interest, 5% or more of the shares): the two rates and the bracket limit per year (one table lists 2024, 2025 and 2026). NOTE: the fisin2025 page repeats the 2024 Box 2 text (33% above 67,000): the Box 2 page is the one that matches the law.' },
  { id: 'nl-bd-box3', method: 'page-extract', url: 'https://www.belastingdienst.nl/wps/wcm/connect/nl/box-3/content/berekening-box-3-inkomen-2026', cells: ['NL:WEALTH_NET'],
    extract: 'Box 3 per year (page name ends in the year: berekening-box-3-inkomen-2024 / -2025 / -2026): the tax rate, the heffingsvrij vermogen, the schuldendrempel and the three fixed return percentages (banktegoeden, beleggingen en andere bezittingen, schulden). Effective rate = tax rate x return percentage: derived, so say so in the note.' },
  { id: 'nl-bd-erf', method: 'page-extract', url: 'https://www.belastingdienst.nl/wps/wcm/connect/nl/erfbelasting/content/tarieven-erfbelasting', cells: ['NL:INHERITANCE_DIRECT', 'NL:INHERITANCE_OTHER'],
    extract: 'Inheritance tax rates per group (partner/child 10%/20%, grandchildren 18%/36%, others 30%/40%), the bracket limit, and the exemptions page (.../vrijstelling-erfbelasting). The current-year pages are overwritten each January: for 2025 and 2024 use the dated Wayback snapshots or the year-named pages (tarieven-erfbelasting-2024, vrijstelling-erfbelasting-2024). A page titled with the wrong year is not a source for that year.' },
  { id: 'nl-statute-wht', method: 'page-extract', url: 'https://wetten.overheid.nl/BWBR0002515', cells: ['NL:WHT_DIVIDEND', 'NL:WHT_INTEREST'],
    extract: 'Wet op de dividendbelasting 1965 art. 5 (15% of the proceeds; versions by date: /2024-01-01, /2025-01-01). Conditional withholding tax: Wet bronbelasting 2021 (BWBR0042952) art. 4.1: the highest corporate income tax percentage, only on payments to affiliated companies in listed low-tax or non-cooperative jurisdictions.' },
  { id: 'nl-low-tax-list', method: 'page-extract', url: 'https://wetten.overheid.nl/BWBR0041785', cells: ['gate:NL:blacklist:MU', 'gate:NL:blacklist:SC'],
    extract: 'Regeling laagbelastende staten en niet-coöperatieve rechtsgebieden voor belastingdoeleinden: the jurisdictions named in art. 2 and 2a for the year (versions: /2024-01-01, /2025-01-01, /2026-01-01). Whether Mauritius and Seychelles are named. Seychelles was named as non-cooperative in the 2024 version only.' },
];

writeFileSync(new URL('./recipes.json', import.meta.url), JSON.stringify({ version: 1, updated: '2026-09-30', recipes }, null, 2) + '\n');
const n = (m) => recipes.filter((r) => r.method === m).length;
console.log(`${recipes.length} recipes: ${n('api')} api, ${n('page-extract')} page-extract, ${n('manual')} manual`);
