// Region outlines for one country, projected exactly like the world map (same Natural Earth constants from world.ts):
//   node scripts/gen-regions.mjs BE <regions.geojson> --key NUTS_ID --map BE1=BE-BRU,BE2=BE-VLG,BE3=BE-WAL
//     → src/map/regions/BE.ts   (REGIONS: jurisdiction code → { d: SVG path, bbox })
// <regions.geojson> is a FeatureCollection of the country's sub-units. --key names the property that identifies a unit;
// --map says which jurisdiction code each unit belongs to. Several units may map to one code (provinces dissolved into the
// region that sets the tax), and units not mentioned are ignored. Sources that work: Eurostat GISCO NUTS
// (https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_01M_2021_4326_LEVL_1.geojson, or LEVL_2 / LEVL_3),
// geoBoundaries ADM1 (https://www.geoboundaries.org/api/current/gbOpen/<ISO3>/ADM1/, simpler shapes).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { geoNaturalEarth1, geoPath } from 'd3-geo';
import { merge } from 'topojson-client';
import { topology } from 'topojson-server';

const [iso2, file] = process.argv.slice(2);
const opt = (n) => { const i = process.argv.indexOf(n); return i >= 0 ? process.argv[i + 1] : null; };
const key = opt('--key'), mapArg = opt('--map');
if (!iso2 || !file || !key || !mapArg) { console.error('usage: node scripts/gen-regions.mjs <ISO2> <regions.geojson> --key <property> --map unit=CODE,unit=CODE'); process.exit(2); }
const unitToCode = Object.fromEntries(mapArg.split(',').map((p) => p.split('=')));

const world = readFileSync(new URL('../src/map/world.ts', import.meta.url), 'utf8').match(/PROJ = \{ k: ([\d.]+), tx: ([\d.]+), ty: ([\d.]+) \}/);
if (!world) throw new Error('PROJ not found in src/map/world.ts: run npm run gen:world first');
const projection = geoNaturalEarth1().scale(+world[1]).translate([+world[2], +world[3]]);
const path = geoPath(projection).digits(2);

const gj = JSON.parse(readFileSync(file, 'utf8'));
const feats = gj.features.filter((f) => unitToCode[f.properties[key]]);
const missing = Object.keys(unitToCode).filter((u) => !feats.some((f) => f.properties[key] === u));
if (missing.length) throw new Error(`units not found in ${file} (property ${key}): ${missing.join(', ')}`);

const codes = [...new Set(Object.values(unitToCode))];
const topo = topology(Object.fromEntries(feats.map((f, i) => [`u${i}`, f])));
const r1 = (v) => Math.round(v * 10) / 10;
const regions = {};
for (const code of codes) {
  const geoms = Object.entries(topo.objects).filter(([i]) => unitToCode[feats[+i.slice(1)].properties[key]] === code).map(([, o]) => o);
  const merged = merge(topo, geoms.flatMap((o) => (o.type === 'GeometryCollection' ? o.geometries : [o])).filter((g) => g.type === 'Polygon' || g.type === 'MultiPolygon'));
  const feature = { type: 'Feature', properties: {}, geometry: merged };
  const [[x0, y0], [x1, y1]] = path.bounds(feature);
  regions[code] = { d: path(feature), bbox: [r1(x0), r1(y0), r1(x1), r1(y1)] };
}
mkdirSync(new URL('../src/map/regions/', import.meta.url), { recursive: true });
const out = new URL(`../src/map/regions/${iso2}.ts`, import.meta.url);
writeFileSync(out, [`// GENERATED by scripts/gen-regions.mjs from ${file.split(/[\\/]/).pop()} (${key}). Do not edit.`,
  `export const REGIONS: Record<string, { d: string; bbox: [number, number, number, number] }> = ${JSON.stringify(regions, null, 1)};`, ''].join('\n'));
console.log(`wrote src/map/regions/${iso2}.ts: ${codes.join(', ')} (${Object.values(regions).reduce((n, r) => n + r.d.length, 0) / 1000 | 0} KB of path data)`);
