// Pre-computes the dashboard's world map so the browser downloads no d3, topojson or atlas:
//   npm run gen:world   → src/map/world.ts
// Natural Earth projection, fitted to 960 px wide. Each country: ISO2, name, an SVG path (1 decimal), its bounding box,
// and a "focus" box around its largest landmass, so zooming to France shows France and not French Guiana.
// The projection constants (PROJ) are written out so the browser can place a capital with src/map/project.ts.
import { readFileSync, writeFileSync } from 'node:fs';
import { geoArea, geoNaturalEarth1, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import countries from 'i18n-iso-countries';

const W = 960;
const topo = JSON.parse(readFileSync(new URL('../node_modules/world-atlas/countries-50m.json', import.meta.url)));
const all = feature(topo, topo.objects.countries).features.filter((f) => f.properties.name !== 'Antarctica');

const projection = geoNaturalEarth1().fitWidth(W, { type: 'Sphere' });
const path = geoPath(projection).digits(1);
const [k, [tx, ty]] = [projection.scale(), projection.translate()];

const r1 = (v) => Math.round(v * 10) / 10;
const box = ([[x0, y0], [x1, y1]]) => [r1(x0), r1(y0), r1(x1), r1(y1)];
const SPECIAL = { Kosovo: 'XK' };                         // not in the ISO numeric table
const iso2Of = (f) => (f.id ? countries.numericToAlpha2(String(f.id).padStart(3, '0')) : SPECIAL[f.properties.name]) ?? '';

// The largest landmass of a (multi)polygon, by spherical area.
const mainland = (f) => {
  const g = f.geometry;
  if (g.type !== 'MultiPolygon') return f;
  const parts = g.coordinates.map((coordinates) => ({ type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates } }));
  return parts.sort((a, b) => geoArea(b) - geoArea(a))[0];
};

const shapes = all.map((f) => ({ iso2: iso2Of(f), name: f.properties.name, d: path(f), bbox: box(path.bounds(f)), focus: box(path.bounds(mainland(f))) }))
  .filter((s) => s.d);

const x0 = Math.min(...shapes.map((s) => s.bbox[0])), y0 = Math.min(...shapes.map((s) => s.bbox[1]));
const x1 = Math.max(...shapes.map((s) => s.bbox[2])), y1 = Math.max(...shapes.map((s) => s.bbox[3]));
const view = [r1(x0 - 4), r1(y0 - 4), r1(x1 - x0 + 8), r1(y1 - y0 + 8)];

const lines = [
  `// GENERATED by scripts/gen-world.mjs (Natural Earth, world-atlas 50m, ${shapes.length} shapes). Do not edit.`,
  `export const PROJ = { k: ${k}, tx: ${tx}, ty: ${ty} };`,
  `/** viewBox of the whole world (Antarctica left out). */`,
  `export const WORLD_VIEW: [number, number, number, number] = ${JSON.stringify(view)};`,
  `export interface CountryShape { iso2: string; name: string; d: string; bbox: [number, number, number, number]; focus: [number, number, number, number] }`,
  `export const SHAPES: CountryShape[] = [`,
  ...shapes.map((s) => `  ${JSON.stringify(s)},`),
  `];`, '',
];
writeFileSync(new URL('../src/map/world.ts', import.meta.url), lines.join('\n'));
const kb = (lines.join('\n').length / 1024).toFixed(0);
console.log(`wrote src/map/world.ts: ${shapes.length} shapes (${shapes.filter((s) => s.iso2).length} with an ISO code), ${kb} KB, view ${view.join(' ')}`);
