-- GENERATED by research/apply-run.mjs from 2026-10-02-msci.json (mode: history) — do not edit.
-- Every value traces to a recipe in research/recipes.json.
set search_path = offshore_insights;


-- index return MSCI_WORLD 2024 gross USD ← msci-world-usd-annual
insert into market_return (index_code, index_name, year, total_return_pct, basis, currency, source, source_url, verified_on) values ('MSCI_WORLD', 'MSCI World Index', 2024, 19.19, 'gross', 'USD', 'MSCI World Index (USD) factsheet, 31 Aug 2026, gross returns', 'https://www.msci.com/documents/10199/178e6643-6ae6-47b9-82be-e1fc565ededb', '2026-10-02') on conflict (index_code, year, basis, currency) do update set total_return_pct = excluded.total_return_pct, index_name = excluded.index_name, source = excluded.source, source_url = excluded.source_url, verified_on = excluded.verified_on;
-- index return MSCI_WORLD 2025 gross USD ← msci-world-usd-annual
insert into market_return (index_code, index_name, year, total_return_pct, basis, currency, source, source_url, verified_on) values ('MSCI_WORLD', 'MSCI World Index', 2025, 21.6, 'gross', 'USD', 'MSCI World Index (USD) factsheet, 31 Aug 2026, gross returns', 'https://www.msci.com/documents/10199/178e6643-6ae6-47b9-82be-e1fc565ededb', '2026-10-02') on conflict (index_code, year, basis, currency) do update set total_return_pct = excluded.total_return_pct, index_name = excluded.index_name, source = excluded.source, source_url = excluded.source_url, verified_on = excluded.verified_on;

reset search_path;
