-- GENERATED by research/apply-run.mjs from 2026-10-02-NL-parked.json (mode: history) — do not edit.
-- Every value traces to a recipe in research/recipes.json.
set search_path = offshore_insights;


-- gap NL advisors
insert into research_item (jurisdiction_code, item, status, detail, where_to_get, checked_on) values ('NL', 'advisors', 'blocked', 'Parked: Hentus paused the firms search on 2026-10-02.', 'Nothing to fetch. Restart with /find-advisors Netherlands when you want it.', '2026-10-02') on conflict (jurisdiction_code, item) do update set status = excluded.status, detail = excluded.detail, where_to_get = excluded.where_to_get, checked_on = excluded.checked_on;

reset search_path;
