-- GENERATED by research/fetch-fx.mjs (recipe fx-eur) — do not edit.
set search_path = offshore_insights;
insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('EUR', 1.00000000, '2026-09-30', 'https://open.er-api.com/v6/latest/EUR') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;
insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('GBP', 1.16618076, '2026-09-30', 'https://open.er-api.com/v6/latest/EUR') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;
insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('ZAR', 0.05374514, '2026-09-30', 'https://open.er-api.com/v6/latest/EUR') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;
insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('CHF', 1.05685008, '2026-09-30', 'https://open.er-api.com/v6/latest/EUR') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;
insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('MUR', 0.01852020, '2026-09-30', 'https://open.er-api.com/v6/latest/EUR') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;
insert into fx_rate (currency, eur_per_unit, as_of, source_url) values ('SCR', 0.06203388, '2026-09-30', 'https://open.er-api.com/v6/latest/EUR') on conflict (currency) do update set eur_per_unit = excluded.eur_per_unit, as_of = excluded.as_of, source_url = excluded.source_url;
reset search_path;
