-- Generated from research/runs/2026-09-30-wealth.json (manual wealth recipes). Upsert per (country, year, source).
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('DE', 2025, 2648000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('GB', 2025, 2428000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('FR', 2025, 2388000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('IT', 2025, 1235000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('ES', 2025, 1077000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('CH', 2025, 944000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('BE', 2025, 556000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('PT', 2025, 181000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, millionaires, source, source_url, verified_on) values ('ZA', 2025, 97000, 'UBS Global Wealth Report 2026', 'https://www.ubs.com/global/en/wealthmanagement/insights/global-wealth-report.html', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set millionaires = excluded.millionaires, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('DE', 2026, 38215, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('GB', 2026, 27876, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('FR', 2026, 21518, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('CH', 2026, 17692, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('IT', 2026, 15433, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('ES', 2026, 9186, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('PT', 2026, 2187, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('ZA', 2026, 1347, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('DE', 2021, 28942, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('GB', 2021, 24871, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('FR', 2021, 17737, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('CH', 2021, 12724, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('IT', 2021, 12547, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('ES', 2021, 6478, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('PT', 2021, 1462, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, uhnwi_count, source, source_url, verified_on) values ('ZA', 2021, 1047, 'Knight Frank Wealth Report 2026', 'https://www.knightfrank.com/wealthreport', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set uhnwi_count = excluded.uhnwi_count, source_url = excluded.source_url, verified_on = excluded.verified_on;
insert into offshore_insights.wealth_market (jurisdiction_code, year, business_owners, source, source_url, verified_on) values ('GB', 2025, 1417730, 'DBT Business Population Estimates 2025', 'https://www.gov.uk/government/statistics/business-population-estimates-2025', '2026-09-30')
  on conflict (jurisdiction_code, year, source) do update set business_owners = excluded.business_owners, source_url = excluded.source_url, verified_on = excluded.verified_on;
